services:
  nginx:
    image: nginx:stable-alpine
    container_name: eabms_nginx_local
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: eabms_backend
    volumes:
      - ./backend:/var/www
    env_file:
      - ./backend/.env
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - CORS_ALLOWED_ORIGINS=http://localhost:8080,http://127.0.0.1:8080

    networks:
      - eabms_network


  db:
    container_name: eabms_db_local
    environment:
      MYSQL_DATABASE: backend-api-vue
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
